---

- name: Install from binary when architecture is ARM
  block:
    - name: Download and install package (no checksum)
      become: yes
      unarchive:
        src: "{{ kapacitor_binary_arm }}"
        dest: "{{ kapacitor_binary_location }}"

    - name: Add service
      become: yes
      template:
        src: kapacitor.service.j2
        dest: "/etc/systemd/system/{{ kapacitor_service_name }}.service"

    - name: Run service
      become: yes
      systemd:
        name: "{{ kapacitor_service_name }}"
        state: started
        daemon_reload: yes
        enabled: yes
  when: ansible_architecture.find('v=' ~ 'arm') == -1
